export const MILE_365_FACEBOOK_PAGE_LINK = import.meta.env.VITE_MILE365_FACEBOOK_PAGE_LINK;
export const MILE_365_FACEBOOK_GROUP_LINK = import.meta.env.VITE_MILE365_FACEBOOK_GROUP_LINK;
export const MILE_365_INSTAGRAM_LINK = import.meta.env.VITE_MILE365_INSTAGRAM_LINK;
export const MILE_365_TIKTOK_LINK = import.meta.env.VITE_MILE365_TIKTOK_LINK;
export const MILE_365_STRAVA_LINK = import.meta.env.VITE_MILE365_STRAVA_LINK;